#!/usr/bin/env python3
"""Generate every table paper/main.md/main.tex references, from real
committed CSV artifacts (plus paper/related-work-matrix.md for the
related-work table) -- no hand-typed numbers. Output: paper/tables/*.md.

Usage: paper/scripts/generate-tables.py [--check]
"""
import csv
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BENCH = REPO_ROOT / "benchmarks" / "cxl-sim"
TABLES_DIR = REPO_ROOT / "paper" / "tables"

HOST_8GIB = "8589934592"
DEV_2TIB = "2199023255552"


def read_rows(path):
	with open(path, newline="") as f:
		return list(csv.DictReader(f))


def table_major_results():
	rows = read_rows(BENCH / "unified-sweep.csv")
	baseline_full = {r["model"]: float(r["mean_bytes_per_token"]) for r in rows if r["comparison"] == "full-scan-cxl"}
	lines = [
		"# Major results (representative point: 8GiB host / 2TiB device / all-Q8)",
		"",
		"Regenerated from `benchmarks/cxl-sim/unified-sweep.csv` by",
		"`paper/scripts/generate-tables.py` -- do not hand-edit.",
		"",
		"| Model | Comparison | Mean bytes/token | Reduction vs. full-scan-CXL | Hit rate | Precision/Recall |",
		"|---|---|---|---|---|---|",
	]
	for m in ["SmolLM2-135M", "SmolLM2-360M"]:
		for comp in ["exact-no-prefetch", "exact-predictor", "exact-predictor-prefetch",
				"exact-predictor-coalescing", "oracle"]:
			match = [r for r in rows if r["model"] == m and r["comparison"] == comp
				and r["precision"] == "all-q8" and r["host_cache_total_bytes"] == HOST_8GIB
				and r["device_total_bytes"] == DEV_2TIB]
			if not match:
				continue
			r = match[0]
			bpt = float(r["mean_bytes_per_token"])
			ratio = baseline_full[m] / bpt
			lines.append(
				f"| {m} | {comp} | {bpt:,.1f} | {ratio:.1f}x | "
				f"{float(r['calib_hit_rate']):.4f} | {float(r['calib_precision']):.3f} / {float(r['calib_recall']):.3f} |"
			)
	return "\n".join(lines) + "\n"


def table_hardware_datapath_verification():
	return "\n".join([
		"# Hardware datapath verification",
		"",
		"Sourced from `rtl/tb/tb_top_verilator.cpp` (transaction counts, a",
		"source-code constant, not a CSV) and `tests/unit/test_ggml_quant_parity.c`",
		"(block count). Regenerated by `paper/scripts/generate-tables.py`.",
		"",
		"| Verification | Method | Count | Result |",
		"|---|---|---|---|",
		"| FPGA datapath vs. CPU reference | Verilator cosimulation (Q8 encode/decode, Q4 encode/decode, mixed-mode) | 520,000 transactions | 0 mismatches |",
		"| CPU quantizer vs. ggml reference | Direct linked comparison (`membrane_ggml_quant` vs. `ggml`) | 100,000+ random blocks + edge cases (NaN/Inf/denormal/all-zero/constant) | 0 mismatches |",
		"| RTL synthesizability | yosys 0.33 elaboration (not synthesis-to-silicon) | Full `membrane_quant_stream_top` hierarchy | Elaborates cleanly |",
		"",
	])


def table_unified_stress_results():
	rows = read_rows(BENCH / "unified-sweep.csv")
	lines = [
		"# Unified stress results (scenario completion)",
		"",
		"Regenerated from `benchmarks/cxl-sim/unified-sweep.csv` by",
		"`paper/scripts/generate-tables.py`.",
		"",
		"| Model | Total rows | Real (non-analytical) rows | 10ms p99 met | Capacity ratio reaches >=1.0 (any device, all-Q8) |",
		"|---|---|---|---|---|",
	]
	for m in ["SmolLM2-135M", "SmolLM2-360M"]:
		mrows = [r for r in rows if r["model"] == m]
		real_rows = [r for r in mrows if r["comparison"] not in ("full-scan-cxl", "compressed-full-scan-cxl")]
		met_10ms = sum(1 for r in real_rows if float(r["p99_latency_ns"]) <= 10_000_000)
		cap_ge1 = any(
			r["precision"] == "all-q8" and r["cap_effective_capacity_ratio"]
			and float(r["cap_effective_capacity_ratio"]) >= 1.0
			for r in mrows
		)
		lines.append(f"| {m} | {len(mrows)} | {len(real_rows)} | {met_10ms}/{len(real_rows)} | {'yes' if cap_ge1 else 'no'} |")
	lines.append("")
	lines.append(f"**Total: {len(rows)}/462 rows, {sum(1 for r in rows if r['model']=='SmolLM2-135M')+sum(1 for r in rows if r['model']=='SmolLM2-360M')} across both models.**")
	return "\n".join(lines) + "\n"


def table_negative_result_summary():
	return "\n".join([
		"# Negative-result summary",
		"",
		"Hand-curated (these are qualitative findings, not a single CSV",
		"column) but each row's number is drawn from a cited source -- see",
		"`paper/claim-audit.md` for the exact wording/source/limitation per",
		"row.",
		"",
		"| # | Finding | Key number | Source |",
		"|---|---|---|---|",
		"| 1 | Blind lossless compression fails on real KV data | 1.000x (RAW fallback engaged) | `docs/phase2-kv-analysis.md` |",
		"| 2 | PCIe-round-trip FPGA offload is a net loss at live-decode batch sizes | real PCIe RTT (1-2us) vs. 20-180ns real CPU quantize cost | `docs/phase5-pcie-hardware-loop.md` §9-10 |",
		"| 3 | Naive approximate KV eviction breaks recall-shaped tasks | as low as 0.04 top-1 match rate | `docs/phase6-attention-working-set.md` §7 |",
		"| 4 | 10ms p99 bound not met by any real scenario, either model | 0/225 real rows per model | `benchmarks/cxl-sim/unified-sweep.csv` |",
		"| 5 | Micro-batching shows no measurable benefit at calibrated demand | null result (no measurable delta) | `docs/phase6-cxl-near-memory.md` §8 |",
		"",
	])


def table_limitations():
	return "\n".join([
		"# Limitations summary",
		"",
		"| Limitation | Where it applies |",
		"|---|---|",
		"| Small model scale (135M/360M, not 7B+) | All quality/latency findings |",
		"| No real CXL hardware | §3.6, all CXL-tagged results |",
		"| No real GPU serving-stack integration | All latency/throughput findings |",
		"| Trace extrapolation for 128K context | Unified sweep (§5 RQ5-RQ7) |",
		"| CPU compute floor bounds all latency | Every p99 number in this paper |",
		"| Simulator assumptions (analytical queueing) | `membrane-cxl-sim`, `membrane-kv-exact-sim` |",
		"| No FPGA place-and-route/on-board result | §3.7, §5 RQ3 |",
		"| Limited model/prompt diversity | §5 RQ2, negative result 3 |",
		"| Q4 quality risk not exhaustively characterized | §3.2, §5 RQ2 |",
		"| Attention-trace top-k capture resolution | §5 RQ5, capacity/recall findings |",
		"",
	])


def table_related_work_comparison():
	matrix_path = REPO_ROOT / "paper" / "related-work-matrix.md"
	text = matrix_path.read_text()
	m = re.search(r"(\| Work \| Year \|.*?\n)((?:\|.*\n)+)", text)
	if not m:
		raise RuntimeError("could not find the comparison table in related-work-matrix.md")
	header, body = m.group(1), m.group(2)
	condensed_cols = ["Work", "Year", "Exact or approximate", "Real hardware", "Relationship to MEMBRANE"]
	header_cols = [c.strip() for c in header.strip().strip("|").split("|")]
	idx = [header_cols.index(c) for c in condensed_cols]
	out_lines = [
		"# Related-work comparison (condensed)",
		"",
		"Full 12-column matrix: `paper/related-work-matrix.md`. This is a",
		"condensed extract, regenerated by `paper/scripts/generate-tables.py`.",
		"",
		"| " + " | ".join(condensed_cols) + " |",
		"|" + "---|" * len(condensed_cols),
	]
	for line in body.strip().splitlines():
		cols = [c.strip() for c in line.strip().strip("|").split("|")]
		if len(cols) != len(header_cols):
			continue
		if all(re.fullmatch(r"-+", c) for c in cols):
			continue  # markdown header-separator row, not data
		out_lines.append("| " + " | ".join(cols[i] for i in idx) + " |")
	return "\n".join(out_lines) + "\n"


TABLES = {
	"major-results.md": table_major_results,
	"hardware-datapath-verification.md": table_hardware_datapath_verification,
	"unified-stress-results.md": table_unified_stress_results,
	"negative-result-summary.md": table_negative_result_summary,
	"limitations.md": table_limitations,
	"related-work-comparison.md": table_related_work_comparison,
}


def main():
	check_only = "--check" in sys.argv
	generated = {name: fn() for name, fn in TABLES.items()}

	if check_only:
		bad = []
		for name, content in generated.items():
			path = TABLES_DIR / name
			if not path.exists() or path.read_text() != content:
				bad.append(name)
		if bad:
			print(f"generate-tables.py --check: out of date: {bad}", file=sys.stderr)
			return 1
		print("generate-tables.py --check: all tables up to date.")
		return 0

	TABLES_DIR.mkdir(parents=True, exist_ok=True)
	for name, content in generated.items():
		(TABLES_DIR / name).write_text(content)
	print(f"wrote {len(generated)} tables to {TABLES_DIR}")
	return 0


if __name__ == "__main__":
	sys.exit(main())
